language: php

## Run on container environment
sudo: false

env:
    - NETTE=3.0
    - NETTE=master

php:
    - 7.1
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: 7.2
        - php: nightly

before_install:
    - composer self-update
    - php tests/prepare-composer.php

install:
    - composer install --no-interaction --prefer-dist

script:
    - vendor/bin/tester tests -s -c tests/php-unix.ini -p php
    - vendor/bin/phpstan analyse --no-progress

after_failure:
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

cache:
  directories:
    - $HOME/.composer/cache
